server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: ms-clientes

  datasource:
    url: jdbc:postgresql://localhost:5433/clientes_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest