services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  clientes-db:
    image: postgres:16
    container_name: clientes-db
    environment:
      POSTGRES_DB: clientes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - clientes_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clientes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  cuentas-db:
    image: postgres:16
    container_name: cuentas-db
    environment:
      POSTGRES_DB: cuentas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - cuentas_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cuentas_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  clientes-service:
    build:
      context: ./ms-clientes
      dockerfile: Dockerfile
    container_name: clientes-service
    depends_on:
      clientes-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://clientes-db:5432/clientes_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  cuentas-service:
    build:
      context: ./ms-cuentas
      dockerfile: Dockerfile
    container_name: cuentas-service
    depends_on:
      cuentas-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://cuentas-db:5432/cuentas_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

volumes:
  clientes_data:
  cuentas_data: